services:
  web:
    build: .
    container_name: site_sophie_web
    ports:
      - "8080:80"
    volumes:
      - ./covers:/usr/share/nginx/html/covers:ro
      - ./scans:/usr/share/nginx/html/scans:ro
      - ./authors:/usr/share/nginx/html/authors:ro
    restart: unless-stopped
