"""initial schema

Revision ID: 52d20cb20392
Revises: 
Create Date: 2026-06-03 01:46:38.901766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d20cb20392'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'author', name='user_role'), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('favo', sa.String(length=2000), nullable=True),
    sa.Column('avatar_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('book', 'comic', 'drawing', name='work_section'), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('blurb', sa.String(length=2000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('shape', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('cover_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'slug', name='uq_works_author_slug')
    )
    op.create_index(op.f('ix_works_author_id'), 'works', ['author_id'], unique=False)
    op.create_index(op.f('ix_works_section'), 'works', ['section'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('scan_path', sa.String(length=512), nullable=True),
    sa.Column('html_path', sa.String(length=512), nullable=True),
    sa.Column('illo_label', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'idx', name='uq_pages_work_idx')
    )
    op.create_index(op.f('ix_pages_work_id'), 'pages', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_work_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_works_section'), table_name='works')
    op.drop_index(op.f('ix_works_author_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
