"""add enhanced/restyled cover paths

Revision ID: 8b980d0cd92e
Revises: 9269b8353395
Create Date: 2026-06-04 22:05:13.986454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b980d0cd92e'
down_revision = '9269b8353395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('enhanced_cover_path', sa.String(length=512), nullable=True))
    op.add_column('works', sa.Column('restyled_cover_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'restyled_cover_path')
    op.drop_column('works', 'enhanced_cover_path')
    # ### end Alembic commands ###
